spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newsfeed_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Cej4268@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true